import React, { useEffect, useCallback } from 'react';
import i18n from 'i18next';
import { initReactI18next, useTranslation } from 'react-i18next';
import LanguageDetector from 'i18next-browser-languagedetector';
import { supplementalTranslations } from './supplementalTranslations';

type Language = 'EN' | 'FR';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

// A basic dictionary for your translations. 
// You can add all your website's text here over time!
const translations: Record<string, Record<Language, string>> = {
  'Home': { EN: 'Home', FR: 'Accueil' },
  'About': { EN: 'About', FR: 'À propos' },
  'Blog': { EN: 'Blog', FR: 'Blog' },
  'Technicals': { EN: 'Technicals', FR: 'Techniques' },
  'Accessories': { EN: 'Accessories', FR: 'Accessoires' },
  'Professionals': { EN: 'Professionals', FR: 'Professionnels' },
  'Gallery': { EN: 'Gallery', FR: 'Galerie' },
  'FAQs': { EN: 'FAQs', FR: 'FAQ' },
  'Inquiry': { EN: 'Inquiry', FR: 'Demande' },
  'Select Language': { EN: 'Select Language', FR: 'Choisir la langue' },
  'Request a Quote': { EN: 'Request a Quote', FR: 'Demander un devis' },
  'Distinctive': { EN: 'Distinctive', FR: 'Distinctif' },
  'Outdoor.': { EN: 'Outdoor.', FR: 'Extérieur.' },
  'Living.': { EN: 'Living.', FR: 'Vivant.' },
  'Explore Collections': { EN: 'Explore Collections', FR: 'Explorer les collections' },
  'Request Consultation': { EN: 'Request Consultation', FR: 'Demander une consultation' },
  '01 — Durability': { EN: '01 — Durability', FR: '01 — Durabilité' },
  '100% ALUMINIUM': { EN: '100% ALUMINIUM', FR: '100% ALUMINIUM' },
  '02 — Versatility': { EN: '02 — Versatility', FR: '02 — Polyvalence' },
  'ADJUSTABLE LOUVRE': { EN: 'ADJUSTABLE LOUVRE', FR: 'LAME RÉGLABLE' },
  '03 — Engineering': { EN: '03 — Engineering', FR: '03 — Ingénierie' },
  'UNMATCHED SPAN': { EN: 'UNMATCHED SPAN', FR: 'PORTÉE INÉGALÉE' },
  'Uncompromising': { EN: 'Uncompromising', FR: 'Intransigeant' },
  'Quality.': { EN: 'Quality.', FR: 'Qualité.' },
  'Collections': { EN: 'Collections', FR: 'Collections' },
  'Architectural': { EN: 'Architectural', FR: 'Architectural' },
  'Solutions.': { EN: 'Solutions.', FR: 'Solutions.' },
  'Classic Design': { EN: 'Classic Design', FR: 'Design Classique' },
  '3 or 4 Season Options': { EN: '3 or 4 Season Options', FR: 'Options 3 ou 4 Saisons' },
  'Built to handle 36" of Wet Snow at 20ft span, more when columns are closer.': { EN: 'Built to handle 36" of Wet Snow at 20ft span, more when columns are closer.', FR: 'Conçu pour supporter 36 po de neige mouillée avec une portée de 20 pi, et davantage lorsque les colonnes sont plus rapprochées.' },
  'Modern Pergola': { EN: 'Modern Pergola', FR: 'Pergola Moderne' },
  'Sleek Contemporary Look': { EN: 'Sleek Contemporary Look', FR: 'Look Contemporain Élégant' },
  'Custom Design': { EN: 'Custom Design', FR: 'Design Sur Mesure' },
  'Built for you': { EN: 'Built for you', FR: 'Construit pour vous' },
  '4-season fixed corrugated roof structure. Roof is fixed.': { EN: '4-season fixed corrugated roof structure. Roof is fixed.', FR: 'Structure 4 saisons à toit ondulé fixe. Le toit est fixe.' },
  'Classic Pergola Top on Existing Structure': { EN: 'Classic Pergola Top on Existing Structure', FR: 'Toit de Pergola Classique sur Structure Existante' },
  'Retrofit Solution': { EN: 'Retrofit Solution', FR: 'Solution de Rénovation' },
  'A classic pergola top designed to integrate with an existing structure while preserving shade, airflow, and year-round outdoor comfort.': { EN: 'A classic pergola top designed to integrate with an existing structure while preserving shade, airflow, and year-round outdoor comfort.', FR: 'Un toit de pergola classique conçu pour s’intégrer à une structure existante tout en préservant l’ombre, la circulation d’air et le confort extérieur toute l’année.' },
  'Precision Crafted': { EN: 'Precision Crafted', FR: 'Conception de Précision' },
  'The Classic Choice': { EN: 'The Classic Choice', FR: 'Le Choix Classique' },
  'Contemporary Elegance': { EN: 'Contemporary Elegance', FR: 'Élégance Contemporaine' },
  'The Modern Choice': { EN: 'The Modern Choice', FR: 'Le Choix Moderne' },
  'Hardware Selection': { EN: 'Hardware Selection', FR: 'Sélection de Quincaillerie' },
  'German-Engineered': { EN: 'German-Engineered', FR: 'Conception Allemande' },
  'Performance': { EN: 'Performance', FR: 'Performance' },
  'Standard': { EN: 'Standard', FR: 'Standard' },
  'Manual Precision': { EN: 'Manual Precision', FR: 'Précision Manuelle' },
  'Available Upgrade': { EN: 'Available Upgrade', FR: 'Amélioration Disponible' },
  'Somfy Electric': { EN: 'Somfy Electric', FR: 'Électrique Somfy' },
  'Exclusively North American Production': { EN: 'Exclusively North American Production', FR: 'Production Exclusivement Nord-Américaine' },
  'Original': { EN: 'Original', FR: 'Original' },
  'View Detail': { EN: 'View Detail', FR: 'Voir les Détails' },
  'Company': { EN: 'Company', FR: 'Compagnie' },
  'Our Story': { EN: 'Our Story', FR: 'Notre Histoire' },
  'Craftsmanship': { EN: 'Craftsmanship', FR: 'Artisanat' },
  'Sustainability': { EN: 'Sustainability', FR: 'Durabilité' },
  'Careers': { EN: 'Careers', FR: 'Carrières' },
  'Newsletter': { EN: 'Newsletter', FR: 'Infolettre' },
  'Join': { EN: 'Join', FR: 'S\'inscrire' },
  'Privacy Policy': { EN: 'Privacy Policy', FR: 'Politique de Confidentialité' },
  'Terms of Service': { EN: 'Terms of Service', FR: 'Conditions d\'Utilisation' },
  'Visual Inspiration': { EN: 'Visual Inspiration', FR: 'Inspiration Visuelle' },
  'The Portfolio of': { EN: 'The Portfolio of', FR: 'Le Portfolio de' },
  'Contact': { EN: 'Contact', FR: 'Contact' },
  'MrPergola.com | 100% Aluminum | Adjustable Louvres': { EN: 'MrPergola.com | 100% Aluminum | Adjustable Louvres', FR: 'MrPergola.com | 100 % Aluminium | Lames Ajustables' },
  'Crafted to Canadian Building Code 2020 and ASCE 7-16 Standard | 272km/hr-170mph': { EN: 'Crafted to Canadian Building Code 2020 and ASCE 7-16 Standard | 272km/hr-170mph', FR: 'Conçu selon le Code National du Bâtiment 2020 et la norme ASCE 7-16 | 272km/h-170mph' },
  'Made In Canada with North American Materials': { EN: 'Made In Canada with North American Materials', FR: 'Fabriqué au Canada avec des Matériaux Nord-Américains' },
  '6061-6063-T6 Extrusions': { EN: '6061-6063-T6 Extrusions', FR: 'Extrusions 6061-6063-T6' },
  '10 Year Warranty': { EN: '10 Year Warranty', FR: 'Garantie de 10 Ans' },
  'Excellence': { EN: 'Excellence', FR: 'l\'Excellence' },
  'Signature Showcase': { EN: 'Signature Showcase', FR: 'Vitrine Signature' },
  'The Art of Outdoor Architecture': { EN: 'The Art of Outdoor Architecture', FR: 'L\'Art de l\'Architecture Extérieure' },
  'Project Installation': { EN: 'Project Installation', FR: 'Installation de Projet' },
  'Bespoke Pergola': { EN: 'Bespoke Pergola', FR: 'Pergola Sur Mesure' },
  'Testimonials': { EN: 'Testimonials', FR: 'Témoignages' },
  'What Our': { EN: 'What Our', FR: 'Ce Que Nos' },
  'Customers': { EN: 'Customers', FR: 'Clients' },
  'Say': { EN: 'Say', FR: 'Disent' },
  'Partnerships': { EN: 'Partnerships', FR: 'Partenariats' },
  'Architects': { EN: 'Architects', FR: 'Architectes' },
  '& Designers.': { EN: '& Designers.', FR: '& Designers.' },
  'CAD & BIM Support': { EN: 'CAD & BIM Support', FR: 'Support CAO et BIM' },
  'Bespoke Engineering': { EN: 'Bespoke Engineering', FR: 'Ingénierie Sur Mesure' },
  'Enhancements': { EN: 'Enhancements', FR: 'Améliorations' },
  'Additions.': { EN: 'Additions.', FR: 'Ajouts.' },
  'Engineering Excellence': { EN: 'Engineering Excellence', FR: 'Excellence en Ingénierie' },
  'Technically': { EN: 'Technically', FR: 'Techniquement' },
  'Superior.': { EN: 'Superior.', FR: 'Supérieur.' },
  'Structural Grade': { EN: 'Structural Grade', FR: 'Qualité Structurelle' },
  '3-Season Permanent': { EN: '3-Season Permanent', FR: 'Permanent 3 Saisons' },
  'The Snow Beast': { EN: 'The Snow Beast', FR: 'La Bête des Neiges' },
  '4-Season Permanent': { EN: '4-Season Permanent', FR: 'Permanent 4 Saisons' },
  'Real Science.': { EN: 'Real Science.', FR: 'Vraie Science.' },
  'No Hacks.': { EN: 'No Hacks.', FR: 'Pas de Raccourcis.' },
  'Support': { EN: 'Support', FR: 'Soutien' },
  'Common': { EN: 'Common', FR: 'Questions' },
  'Inquiries.': { EN: 'Inquiries.', FR: 'Fréquentes.' },
  
  // Paragraphs & Long Descriptions
  'Highly customizable with louvres showing and water falling from the top in any direction. The 4-Season option handles up to 36" of snow, perfect for winter BBQs.': { EN: 'Highly customizable with louvres showing and water falling from the top in any direction. The 4-Season option handles up to 36" of snow, perfect for winter BBQs.', FR: 'Hautement personnalisable avec des lames apparentes et une chute d\'eau depuis le sommet dans n\'importe quelle direction. L\'option 4 saisons supporte jusqu\'à 36" de neige, parfait pour les barbecues d\'hiver.' },
  'Boxed-in design where water flows internally down the columns. Purpose-built for the North American market with a clean, rectangular or square profile.': { EN: 'Boxed-in design where water flows internally down the columns. Purpose-built for the North American market with a clean, rectangular or square profile.', FR: 'Design encastré où l\'eau s\'écoule intérieurement dans les colonnes. Conçu spécifiquement pour le marché nord-américain avec un profil propre, rectangulaire ou carré.' },
  'Rotating louvred systems that transform your backyard. Summer is no longer too hot, and rain is no longer a problem for your outdoor lifestyle.': { EN: 'Rotating louvred systems that transform your backyard. Summer is no longer too hot, and rain is no longer a problem for your outdoor lifestyle.', FR: 'Systèmes de lames rotatives qui transforment votre cour arrière. L\'été n\'est plus trop chaud, et la pluie n\'est plus un problème pour votre style de vie extérieur.' },
  'Mr. Pergola offers you three distinct choices. A Classic Design in 3 or 4 Season options and a sleek Modern design for those who appreciate contemporary minimalism.': { EN: 'Mr. Pergola offers you three distinct choices. A Classic Design in 3 or 4 Season options and a sleek Modern design for those who appreciate contemporary minimalism.', FR: 'Mr. Pergola vous offre trois choix distincts. Un design classique en options 3 ou 4 saisons et un design moderne élégant pour ceux qui apprécient le minimalisme contemporain.' },
  'A timeless aesthetic featuring exposed louvres that direct water runoff in any direction you choose. Available in both ': { EN: 'A timeless aesthetic featuring exposed louvres that direct water runoff in any direction you choose. Available in both ', FR: 'Une esthétique intemporelle avec des lames apparentes qui dirigent l\'écoulement de l\'eau dans la direction de votre choix. Disponible dans les variantes ' },
  '3 and 4 Season': { EN: '3 and 4 Season', FR: '3 et 4 saisons' },
  ' varieties.': { EN: ' varieties.', FR: '.' },
  'While the 3-Season model requires open louvres during snowfall, our ': { EN: 'While the 3-Season model requires open louvres during snowfall, our ', FR: 'Bien que le modèle 3 saisons nécessite des lames ouvertes pendant les chutes de neige, notre ' },
  '4-Season option': { EN: '4-Season option', FR: 'option 4 saisons' },
  ' is engineered for true year-round living. Built to handle up to ': { EN: ' is engineered for true year-round living. Built to handle up to ', FR: ' est conçu pour une vraie vie à l\'année. Conçu pour supporter jusqu\'à ' },
  '36” of snow': { EN: '36” of snow', FR: '36 po de neige' },
  '.': { EN: '.', FR: '.' },
  'For those seeking a sleek, minimalist silhouette. The MODERN is purpose-built with high-tensile materials specifically for the North American climate.': { EN: 'For those seeking a sleek, minimalist silhouette. The MODERN is purpose-built with high-tensile materials specifically for the North American climate.', FR: 'Pour ceux qui recherchent une silhouette épurée et minimaliste. Le MODERNE est construit avec des matériaux à haute résistance spécifiquement pour le climat nord-américain.' },
  'Sophisticated ': { EN: 'Sophisticated ', FR: 'Design ' },
  '"boxed-in"': { EN: '"boxed-in"', FR: '"encastré"' },
  ' design where water flows internally through columns. Maintains a strict architectural profile while retaining full control over drainage direction.': { EN: ' design where water flows internally through columns. Maintains a strict architectural profile while retaining full control over drainage direction.', FR: ' sophistiqué où l\'eau s\'écoule à l\'intérieur des colonnes. Maintient un profil architectural strict tout en conservant un contrôle total sur la direction du drainage.' },
  'Sophisticated Sleek Contemporary Design where water flows internally through columns. Maintains a strict architectural profile while retaining full control over drainage direction.': { EN: 'Sophisticated Sleek Contemporary Design where water flows internally through columns. Maintains a strict architectural profile while retaining full control over drainage direction.', FR: 'Design contemporain élégant et sophistiqué où l\'eau s\'écoule à l\'intérieur des colonnes. Maintient un profil architectural strict tout en conservant un contrôle total sur la direction du drainage.' },
  'Every Mr. Pergola system integrates the world-class ': { EN: 'Every Mr. Pergola system integrates the world-class ', FR: 'Chaque système Mr. Pergola intègre le réducteur de classe mondiale ' },
  'LockDrives 6000n gearbox': { EN: 'LockDrives 6000n gearbox', FR: 'LockDrives 6000n' },
  '. Engineered in Germany for extreme load conditions, this heavy-duty system is designed for the lifetime of your structure.': { EN: '. Engineered in Germany for extreme load conditions, this heavy-duty system is designed for the lifetime of your structure.', FR: '. Conçu en Allemagne pour des conditions de charge extrêmes, ce système robuste est conçu pour la durée de vie de votre structure.' },
  'Reliable, heavy-duty mechanical drive system.': { EN: 'Reliable, heavy-duty mechanical drive system.', FR: 'Système d\'entraînement mécanique robuste et fiable.' },
  'Integrated smart automation for ultimate ease.': { EN: 'Integrated smart automation for ultimate ease.', FR: 'Automatisation intelligente intégrée pour une facilité ultime.' },
  'None of our pergolas come in a box from China.': { EN: 'None of our pergolas come in a box from China.', FR: 'Aucune de nos pergolas ne provient d\'une boîte de Chine.' },
  'Inspiration — ': { EN: 'Inspiration — ', FR: 'Inspiration — ' },
  'Architectural Systems': { EN: 'Architectural Systems', FR: 'Systèmes Architecturaux' },
  'Designed for backyards... Built for real life! \n              Precision engineered architectural solutions for \n              Sun, Rain, and Snow.': { EN: 'Designed for backyards... Built for real life! \n              Precision engineered architectural solutions for \n              Sun, Rain, and Snow.', FR: 'Conçu pour les cours arrière... Construit pour la vraie vie ! Solutions architecturales de précision pour le soleil, la pluie et la neige.' },
  'Classic Pergola': { EN: 'Classic Pergola', FR: 'Pergola Classique' },
  'Modern-Integrated': { EN: 'Modern-Integrated', FR: 'Moderne-Intégré' },
  'Artisan Finishes': { EN: 'Artisan Finishes', FR: 'Finitions Artisanales' },
  'Commercial Systems': { EN: 'Commercial Systems', FR: 'Systèmes Commerciaux' },
  'Subscribe to receive updates on new collections and design inspiration.': { EN: 'Subscribe to receive updates on new collections and design inspiration.', FR: 'Abonnez-vous pour recevoir des mises à jour sur les nouvelles collections et l\'inspiration.' },
  'Email Address': { EN: 'Email Address', FR: 'Adresse Courriel' },
  '© 2026 Mr. Pergola. All Rights Reserved.': { EN: '© 2026 Mr. Pergola. All Rights Reserved.', FR: '© 2026 Mr. Pergola. Tous Droits Réservés.' },
  'The 4-Season Classic Pergola is exactly what we needed. We use our BBQ even in the middle of a Canadian winter now. Highly recommended!': { EN: 'The 4-Season Classic Pergola is exactly what we needed. We use our BBQ even in the middle of a Canadian winter now. Highly recommended!', FR: 'La pergola classique 4 saisons est exactement ce dont nous avions besoin. Nous utilisons notre barbecue même au milieu de l\'hiver canadien maintenant. Fortement recommandé !' },
  'We chose the Modern Design for our rooftop patio. The engineering is incredible, and the internal drainage system works perfectly even in heavy downpours.': { EN: 'We chose the Modern Design for our rooftop patio. The engineering is incredible, and the internal drainage system works perfectly even in heavy downpours.', FR: 'Nous avons choisi le design moderne pour notre terrasse sur le toit. L\'ingénierie est incroyable, et le système de drainage interne fonctionne parfaitement même lors de fortes averses.' },
  'Installation was professional and the final product is stunning. It’s not just a pergola; it’s an architectural statement that added real value to our home.': { EN: 'Installation was professional and the final product is stunning. It’s not just a pergola; it’s an architectural statement that added real value to our home.', FR: 'L\'installation a été professionnelle et le produit final est magnifique. Ce n\'est pas seulement une pergola ; c\'est une déclaration architecturale qui a ajouté une réelle valeur à notre maison.' },
  'Montreal, QC': { EN: 'Montreal, QC', FR: 'Montréal, QC' },
  'Toronto, ON': { EN: 'Toronto, ON', FR: 'Toronto, ON' },
  'Vancouver, BC': { EN: 'Vancouver, BC', FR: 'Vancouver, C-B' },
  'We collaborate with the world\'s leading architects and landscape designers to integrate our systems into the most prestigious projects.': { EN: 'We collaborate with the world\'s leading architects and landscape designers to integrate our systems into the most prestigious projects.', FR: 'Nous collaborons avec les principaux architectes et paysagistes mondiaux pour intégrer nos systèmes dans les projets les plus prestigieux.' },
  'Access our comprehensive library of technical drawings and 3D models for seamless architectural integration.': { EN: 'Access our comprehensive library of technical drawings and 3D models for seamless architectural integration.', FR: 'Accédez à notre bibliothèque complète de dessins techniques et de modèles 3D pour une intégration architecturale sans faille.' },
  'Our in-house engineering team provides dedicated assistance for complex structural requirements and site-specific adaptations.': { EN: 'Our in-house engineering team provides dedicated assistance for complex structural requirements and site-specific adaptations.', FR: 'Notre équipe d\'ingénierie interne fournit une assistance dédiée pour les exigences structurelles complexes et les adaptations spécifiques au site.' },
  'Motorized Screens': { EN: 'Motorized Screens', FR: 'Moustiquaires Motorisées' },
  'Protect against insects and wind while maintaining visibility.': { EN: 'Protect against insects and wind while maintaining visibility.', FR: 'Protège contre les insectes et le vent tout en maintenant la visibilité.' },
  'Integrated LED Lighting': { EN: 'Integrated LED Lighting', FR: 'Éclairage DEL Intégré' },
  'Dimmable lighting systems built directly into the frame.': { EN: 'Dimmable lighting systems built directly into the frame.', FR: 'Systèmes d\'éclairage à intensité variable intégrés directement dans le cadre.' },
  'Architectural slats for enhanced privacy and shade.': { EN: 'Architectural slats for enhanced privacy and shade.', FR: 'Lattes architecturales pour plus d\'intimité et d\'ombre.' },
  'High Grade Steel': { EN: 'High Grade Steel', FR: 'Acier de Haute Qualité' },
  'Double powder coated for superior protection. 10g steel corners for maximum rigidity.': { EN: 'Double powder coated for superior protection. 10g steel corners for maximum rigidity.', FR: 'Double revêtement en poudre pour une protection supérieure. Coins en acier 10g pour une rigidité maximale.' },
  '88 lbs/sqft': { EN: '88 lbs/sqft', FR: '88 lb/pi²' },
  'Double anyone else\'s claims. Validated by two independent engineering firms.': { EN: 'Double anyone else\'s claims. Validated by two independent engineering firms.', FR: 'Le double des affirmations de quiconque. Validé par deux cabinets d\'ingénieurs indépendants.' },
  'Cat4 Hurricane': { EN: 'Cat4 Hurricane', FR: 'Ouragan Cat 4' },
  'Wind-load tested up to 156mph-251km/hr for coastal and rooftop safety.': { EN: 'Wind-load tested up to 156mph-251km/hr for coastal and rooftop safety.', FR: 'Testé pour la charge de vent jusqu\'à 156mph-251km/h pour la sécurité côtière et sur les toits.' },
  '20ft Spans': { EN: '20ft Spans', FR: 'Portées de 20 pi' },
  'Unmatched 20ft depth between columns without structural compromise.': { EN: 'Unmatched 20ft depth between columns without structural compromise.', FR: 'Profondeur inégalée de 20 pieds entre les colonnes sans compromis structurel.' },
  '"One of our biggest points of pride is that when engineers come to see our product, they buy our product."': { EN: '"One of our biggest points of pride is that when engineers come to see our product, they buy our product."', FR: '"L\'une de nos plus grandes fiertés est que lorsque les ingénieurs viennent voir notre produit, ils achètent notre produit."' },
  'We ask our clients to pay us a visit and compare the sheer quality difference between a Mr. Pergola system compared to, literally, any other pergola on the market. Bar None! Mr. Pergola comes on top.': { EN: 'We ask our clients to pay us a visit and compare the sheer quality difference between a Mr. Pergola system compared to, literally, any other pergola on the market. Bar None! Mr. Pergola comes on top.', FR: 'Nous demandons à nos clients de nous rendre visite et de comparer la différence de qualité pure entre un système Mr. Pergola par rapport à toute autre pergola sur le marché. Sans exception ! Mr. Pergola arrive en tête.' },
  'We studied our competitors, even going as far as buying competing products to see what works and doesn\'t for the North American market. We came up with two distinct systems for two different use cases: 3-Season and 4-Season.': { EN: 'We studied our competitors, even going as far as buying competing products to see what works and doesn\'t for the North American market. We came up with two distinct systems for two different use cases: 3-Season and 4-Season.', FR: 'Nous avons étudié nos concurrents, allant même jusqu\'à acheter des produits concurrents. Nous avons conçu deux systèmes distincts pour deux cas d\'utilisation différents : 3 saisons et 4 saisons.' },
  'We DO NOT use Stainless Steel to build our corners—they are simply not as strong as steel. While competitors use flimsy bent sheet metal with #12 screws, we use 10g steel and 6 Grade-8, half-inch bolts for each corner.': { EN: 'We DO NOT use Stainless Steel to build our corners—they are simply not as strong as steel. While competitors use flimsy bent sheet metal with #12 screws, we use 10g steel and 6 Grade-8, half-inch bolts for each corner.', FR: 'Nous N\'UTILISONS PAS d\'acier inoxydable pour nos coins — ils ne sont pas aussi solides que l\'acier. Alors que les concurrents utilisent de la tôle fragile, nous utilisons de l\'acier 10g et 6 boulons d\'un demi-pouce de Grade-8.' },
  '"Our unique corner bracket also has a 4”x 4” HSS underneath going down 12” to help against the wind. We\'ve installed these on lakes and rooftops without a single problem."': { EN: '"Our unique corner bracket also has a 4”x 4” HSS underneath going down 12” to help against the wind. We\'ve installed these on lakes and rooftops without a single problem."', FR: '"Notre support de coin unique a également un HSS de 4”x 4” en dessous descendant de 12” pour aider contre le vent. Nous les avons installés sur des lacs et des toits sans un seul problème."' },
  'The only pergola in the world that can handle 3 feet of wet snow (22,000lbs on a 16×16). Our snow load capacity is 88 pounds per square foot—double anyone else\'s claims.': { EN: 'The only pergola in the world that can handle 3 feet of wet snow (22,000lbs on a 16×16). Our snow load capacity is 88 pounds per square foot—double anyone else\'s claims.', FR: 'La seule pergola au monde capable de supporter 3 pieds de neige mouillée (22 000 lb sur un 16×16). Notre capacité de charge de neige est de 88 livres par pied carré — le double des affirmations de quiconque.' },
  '20ft width and 20ft depth with only 4 columns.': { EN: '20ft width and 20ft depth with only 4 columns.', FR: 'Largeur de 20 pi et profondeur de 20 pi avec seulement 4 colonnes.' },
  '1/4" thick double-coated steel corner brackets.': { EN: '1/4" thick double-coated steel corner brackets.', FR: 'Supports de coin en acier à double revêtement de 1/4" d\'épaisseur.' },
  'Louvres (blades) can surpass the frame by 4ft without dropping or bending.': { EN: 'Louvres (blades) can surpass the frame by 4ft without dropping or bending.', FR: 'Les lames peuvent dépasser le cadre de 4 pi sans tomber ni se plier.' },
  '"We don\'t simply put some weight on the pergola and make a claim; we invested heavily so that we can guarantee our claims with specialized engineering firms."': { EN: '"We don\'t simply put some weight on the pergola and make a claim; we invested heavily so that we can guarantee our claims with specialized engineering firms."', FR: '"Nous ne mettons pas simplement du poids sur la pergola pour faire une affirmation ; nous avons investi massivement pour pouvoir garantir nos affirmations avec des cabinets d\'ingénieurs spécialisés."' },
  'Well over a thousand hours of engineering went into our design and development. Add another small fortune for testing and validation by two engineers who signed off on the design.': { EN: 'Well over a thousand hours of engineering went into our design and development. Add another small fortune for testing and validation by two engineers who signed off on the design.', FR: 'Plus de mille heures d\'ingénierie ont été consacrées à notre conception. Ajoutez une petite fortune pour les tests et la validation par deux ingénieurs qui ont approuvé la conception.' },
  'Made in Canada with Canadian Aluminum and American Steel.': { EN: 'Made in Canada with Canadian Aluminum and American Steel.', FR: 'Fabriqué au Canada avec de l\'aluminium canadien et de l\'acier américain.' },
  '*** NONE OF OUR PERGOLAS COME IN A BOX FROM CHINA! ***': { EN: '*** NONE OF OUR PERGOLAS COME IN A BOX FROM CHINA! ***', FR: '*** AUCUNE DE NOS PERGOLAS NE PROVIENT D\'UNE BOÎTE DE CHINE ! ***' },
  'What is the standard lead time for an installation?': { EN: 'What is the standard lead time for an installation?', FR: 'Quel est le délai standard pour une installation ?' },
  'Typical lead times range from 8 to 12 weeks, depending on the complexity of the customization and current production schedule.': { EN: 'Typical lead times range from 8 to 12 weeks, depending on the complexity of the customization and current production schedule.', FR: 'Les délais typiques varient de 8 à 12 semaines, selon la complexité de la personnalisation et le calendrier de production actuel.' },
  'Are the structures really hurricane rated?': { EN: 'Are the structures really hurricane rated?', FR: 'Les structures sont-elles vraiment classées pour les ouragans ?' },
  'Yes, our systems are engineered to meet ASCE 7-16 standards and are tested to withstand wind loads up to 160 MPH.': { EN: 'Yes, our systems are engineered to meet ASCE 7-16 standards and are tested to withstand wind loads up to 160 MPH.', FR: 'Oui, nos systèmes sont conçus pour répondre aux normes ASCE 7-16 et sont testés pour résister à des charges de vent allant jusqu\'à 160 MPH.' },
  'Can the louvers be controlled remotely?': { EN: 'Can the louvers be controlled remotely?', FR: 'Les lames peuvent-elles être contrôlées à distance ?' },
  'Absolutely. Our systems feature motorized control via remote, smartphone app, or integration with smart home systems.': { EN: 'Absolutely. Our systems feature motorized control via remote, smartphone app, or integration with smart home systems.', FR: 'Absolument. Nos systèmes disposent d\'un contrôle motorisé via télécommande, application ou intégration avec des systèmes de maison intelligente.' },
  'What maintenance is required?': { EN: 'What maintenance is required?', FR: 'Quel entretien est requis ?' },
  'Our architectural-grade aluminum is low-maintenance. We recommend a simple seasonal cleaning with mild soap and water.': { EN: 'Our architectural-grade aluminum is low-maintenance. We recommend a simple seasonal cleaning with mild soap and water.', FR: 'Notre aluminium de qualité architecturale nécessite peu d\'entretien. Nous recommandons un simple nettoyage saisonnier avec de l\'eau et du savon doux.' },
  
  // --- Missing FAQ Translations Example ---
  'WHAT ARE THE AVAILABLE SIZES?': { EN: 'WHAT ARE THE AVAILABLE SIZES?', FR: 'QUELLES SONT LES TAILLES DISPONIBLES ?' },
  "Every size is possible, we haven't encountered a project we can't handle. For custom size, larger projects, we have engineering resources that validate the build before we even collect a deposit. We can even cover your entire pool if you chose to use it in winter.": { EN: "Every size is possible, we haven't encountered a project we can't handle. For custom size, larger projects, we have engineering resources that validate the build before we even collect a deposit. We can even cover your entire pool if you chose to use it in winter.", FR: "Toutes les tailles sont possibles, nous n'avons pas rencontré de projet que nous ne pouvions pas gérer. Pour des tailles sur mesure ou de grands projets, nos ingénieurs valident la construction avant tout acompte. Nous pouvons même couvrir votre piscine en hiver." },
  'WHAT ARE THE TECHNICAL DESIGN FEATURES OF MR PERGOLA?': { EN: 'WHAT ARE THE TECHNICAL DESIGN FEATURES OF MR PERGOLA?', FR: 'QUELLES SONT LES CARACTÉRISTIQUES TECHNIQUES DE MR PERGOLA ?' },
  'Please see Technicals Page for a complete guide.': { EN: 'Please see Technicals Page for a complete guide.', FR: 'Veuillez consulter la page Techniques pour un guide complet.' },

  // --- Missing FAQs ---
  'WHAT ARE THE AVAILABLE COLORS?': { EN: 'WHAT ARE THE AVAILABLE COLORS?', FR: 'QUELLES SONT LES COULEURS DISPONIBLES ?' },
  'Standard colors are: Black, White, Grey and then almost any color scheme you can think of. Other colors might take an extra 2-4 weeks for delivery.': { EN: 'Standard colors are: Black, White, Grey and then almost any color scheme you can think of. Other colors might take an extra 2-4 weeks for delivery.', FR: 'Les couleurs standards sont : Noir, Blanc, Gris et presque n\'importe quel agencement de couleurs. D\'autres couleurs peuvent nécessiter 2 à 4 semaines de plus.' },
  'WHAT KIND OF PAINT IS USED?': { EN: 'WHAT KIND OF PAINT IS USED?', FR: 'QUEL TYPE DE PEINTURE EST UTILISÉ ?' },
  'All our components are covered with high grade Powder Coating. Powder-Coats are known for keeping their color for at least 10 years before even the slightest discoloration, if any.': { EN: 'All our components are covered with high grade Powder Coating. Powder-Coats are known for keeping their color for at least 10 years before even the slightest discoloration, if any.', FR: 'Tous nos composants sont recouverts d\'un revêtement en poudre de haute qualité. Les revêtements en poudre sont connus pour conserver leur couleur pendant au moins 10 ans.' },
  'WHO INSTALLS IT?': { EN: 'WHO INSTALLS IT?', FR: 'QUI L\'INSTALLE ?' },
  'Two above average handymen (or women) can install it in a day. The bigger sizes might take an extra half day. It was designed with the average person in mind. If you want to be safe, we have installers that will do a guaranteed job. Installation prices range from five hundred to over a thousand dollars for larger projects.': { EN: 'Two above average handymen (or women) can install it in a day. The bigger sizes might take an extra half day. It was designed with the average person in mind. If you want to be safe, we have installers that will do a guaranteed job. Installation prices range from five hundred to over a thousand dollars for larger projects.', FR: 'Deux bons bricoleurs peuvent l\'installer en une journée. Les grandes tailles peuvent prendre une demi-journée supplémentaire. Si vous voulez être rassuré, nous avons des installateurs. Les prix d\'installation varient de 500 $ à plus de 1000 $.' },
  'HOW LONG DOES IT TAKE TO GET OUR PERGOLA?': { EN: 'HOW LONG DOES IT TAKE TO GET OUR PERGOLA?', FR: 'COMBIEN DE TEMPS FAUT-IL POUR OBTENIR NOTRE PERGOLA ?' },
  'Expect to have Mr. Pergola installed in 2-4 weeks. Slight variation during peak season. The sooner you reserve, the better.': { EN: 'Expect to have Mr. Pergola installed in 2-4 weeks. Slight variation during peak season. The sooner you reserve, the better.', FR: 'Attendez-vous à ce que Mr. Pergola soit installé en 2 à 4 semaines. Légère variation en haute saison. Le plus tôt vous réservez, mieux c\'est.' },
  'CAN WE INSTALL MOSQUITO NETS?': { EN: 'CAN WE INSTALL MOSQUITO NETS?', FR: 'POUVONS-NOUS INSTALLER DES MOUSTIQUAIRES ?' },
  'Mr. Pergola is ready to accept roller based hooking system that can hang curtains. You can buy your own mosquito curtains, or we can have a custom sized one made for you. Delivery is an additional three weeks if not ordered at the same time as pergola.': { EN: 'Mr. Pergola is ready to accept roller based hooking system that can hang curtains. You can buy your own mosquito curtains, or we can have a custom sized one made for you. Delivery is an additional three weeks if not ordered at the same time as pergola.', FR: 'Mr. Pergola est prêt à recevoir un système de rouleaux pour rideaux. Vous pouvez acheter vos propres moustiquaires, ou nous pouvons en fabriquer sur mesure. La livraison prend trois semaines de plus.' },
  'CAN WE INSTALL A HEATER?': { EN: 'CAN WE INSTALL A HEATER?', FR: 'POUVONS-NOUS INSTALLER UN CHAUFFAGE ?' },
  'Yes, Mr. Pergola was specially built to handle an array of accessories. Including heater, hammock, mosquito netting, corner tables and more coming soon!': { EN: 'Yes, Mr. Pergola was specially built to handle an array of accessories. Including heater, hammock, mosquito netting, corner tables and more coming soon!', FR: 'Oui, Mr. Pergola a été spécialement conçu pour accueillir divers accessoires. Incluant chauffage, hamac, moustiquaire, tables de coin et plus à venir !' },
  'CAN THE PERGOLA BE ATTACHED TO THE HOUSE (OR RESTAURANT) INSTEAD OF 4 POSTS?': { EN: 'CAN THE PERGOLA BE ATTACHED TO THE HOUSE (OR RESTAURANT) INSTEAD OF 4 POSTS?', FR: 'LA PERGOLA PEUT-ELLE ÊTRE ATTACHÉE À LA MAISON AU LIEU DE 4 POTEAUX ?' },
  'Unfortunately not. The weight requirements are so high that we must have it on 4 posts. The pergola will be very close/almost touching the house where it will look as one. Nevertheless, the 4 post are mandatory since our updated design where the snow load is up to 15000lbs per 250 sq feet. Previous versions were available attached to the house.': { EN: 'Unfortunately not. The weight requirements are so high that we must have it on 4 posts. The pergola will be very close/almost touching the house where it will look as one. Nevertheless, the 4 post are mandatory since our updated design where the snow load is up to 15000lbs per 250 sq feet. Previous versions were available attached to the house.', FR: 'Malheureusement non. Les exigences de poids sont si élevées que nous devons l\'avoir sur 4 poteaux. La pergola sera très proche de la maison. Les 4 poteaux sont obligatoires depuis notre nouveau design.' },
  'WHAT WARRANTY DO YOU OFFER?': { EN: 'WHAT WARRANTY DO YOU OFFER?', FR: 'QUELLE GARANTIE OFFREZ-VOUS ?' },
  'We offer a 10 year limited warranty. Built strong to handle North American climate. From blazing sun to blistering cold and snow. Commercial grade powder coating and Grade:6063 Canadian Aluminum will make your outdoor pristine for years!': { EN: 'We offer a 10 year limited warranty. Built strong to handle North American climate. From blazing sun to blistering cold and snow. Commercial grade powder coating and Grade:6063 Canadian Aluminum will make your outdoor pristine for years!', FR: 'Nous offrons une garantie limitée de 10 ans. Construit solidement pour affronter le climat nord-américain. Le revêtement en poudre commercial et l\'aluminium 6063 rendront votre extérieur impeccable pour des années !' },
  'WHERE IS Mr.PERGOLA MADE?': { EN: 'WHERE IS Mr.PERGOLA MADE?', FR: 'OÙ EST FABRIQUÉ MR.PERGOLA ?' },
  'Mr.Pergola is entirely made in North American and assembled in Montreal Canada following the highest standards of North American production using American and Canadian Aluminum and Steel.': { EN: 'Mr.Pergola is entirely made in North American and assembled in Montreal Canada following the highest standards of North American production using American and Canadian Aluminum and Steel.', FR: 'Mr.Pergola est entièrement fabriqué en Amérique du Nord et assemblé à Montréal en utilisant de l\'aluminium et de l\'acier américains et canadiens.' },
  'It was designed and validated by American and Canadian engineers and Industrial Designers. All parts are from North American suppliers. We pay the extra for Midwest Aluminum Premium to ensure highest quality. Though Quebec has the best aluminum in North America, Pittsburgh has the best steel.': { EN: 'It was designed and validated by American and Canadian engineers and Industrial Designers. All parts are from North American suppliers. We pay the extra for Midwest Aluminum Premium to ensure highest quality. Though Quebec has the best aluminum in North America, Pittsburgh has the best steel.', FR: 'Il a été conçu et validé par des ingénieurs américains et canadiens. Nous payons un supplément pour l\'Aluminium Midwest Premium afin d\'assurer la meilleure qualité.' },
  'WHY ARE YOUR PRICES SO MUCH BETTER THAN YOUR COMPETITORS, WHILE OFFERING THIS TYPE OF HEAVY GRADE ALUMINUM AND STEEL?': { EN: 'WHY ARE YOUR PRICES SO MUCH BETTER THAN YOUR COMPETITORS, WHILE OFFERING THIS TYPE OF HEAVY GRADE ALUMINUM AND STEEL?', FR: 'POURQUOI VOS PRIX SONT-ILS MEILLEURS QUE CEUX DE VOS CONCURRENTS ?' },
  'We are the manufacturer. We sell the strongest pergola in the world direct to consumers and cut out the middleman. Whether you want a Classic Pergola for a timeless solution or a Modern Pergola to fit your backyard\'s upgrades and modern finishes, we have a solution at unbeatable prices.': { EN: 'We are the manufacturer. We sell the strongest pergola in the world direct to consumers and cut out the middleman. Whether you want a Classic Pergola for a timeless solution or a Modern Pergola to fit your backyard\'s upgrades and modern finishes, we have a solution at unbeatable prices.', FR: 'Nous sommes le fabricant. Nous vendons directement aux consommateurs et éliminons les intermédiaires. Nous avons une solution à des prix imbattables.' },
  'WHY DO YOU HAVE 3 TYPES OF PERGOLAS?': { EN: 'WHY DO YOU HAVE 3 TYPES OF PERGOLAS?', FR: 'POURQUOI AVEZ-VOUS 3 TYPES DE PERGOLAS ?' },
  'When this journey began 9 years ago, the founder had bought a pergola for his patio and wished it could serve him in winter (as did everyone who visited). He soon found out there are no real 4-season Pergolas out there. Sure there were some who claimed to be 4-Season/Winter Pergolas but his needs had to fit their design instead of their Pergola fitting his needs.': { EN: 'When this journey began 9 years ago, the founder had bought a pergola for his patio and wished it could serve him in winter (as did everyone who visited). He soon found out there are no real 4-season Pergolas out there. Sure there were some who claimed to be 4-Season/Winter Pergolas but his needs had to fit their design instead of their Pergola fitting his needs.', FR: 'Il y a 9 ans, le fondateur a acheté une pergola et souhaitait qu\'elle lui serve en hiver. Il a vite découvert qu\'il n\'existait pas de véritables pergolas 4 saisons.' },
  'All the manufacturers he found, who offer a pergola with a any real snow load capacity, can only go to a span of 12ft between columns, and his patio was 14ft deep. So as you can read in the About Us page, he got to work and created a product with clear unique capabilities loved by so many across North America from Calgary to NYC.': { EN: 'All the manufacturers he found, who offer a pergola with a any real snow load capacity, can only go to a span of 12ft between columns, and his patio was 14ft deep. So as you can read in the About Us page, he got to work and created a product with clear unique capabilities loved by so many across North America from Calgary to NYC.', FR: 'Tous les fabricants ne pouvaient aller que jusqu\'à une portée de 12 pieds, et son patio faisait 14 pieds. Il a donc créé un produit aux capacités uniques.' },
  'Note: Our products are designed and built according to the American Society of Civil Engineers 7-16 standards (ASCE 7-16 not 7-10) and the Canadian Building Code. We offer the only Pergola that can fit larger patios and terraces with up to 20ft spans between columns. We can go to 20ft DEEP and 20ft WIDE with only 4 posts.': { EN: 'Note: Our products are designed and built according to the American Society of Civil Engineers 7-16 standards (ASCE 7-16 not 7-10) and the Canadian Building Code. We offer the only Pergola that can fit larger patios and terraces with up to 20ft spans between columns. We can go to 20ft DEEP and 20ft WIDE with only 4 posts.', FR: 'Remarque : Nos produits sont conçus selon les normes ASCE 7-16 et le Code national du bâtiment du Canada. Nous offrons la seule pergola pouvant s\'adapter à de grands patios avec des portées de 20 pi.' },
  "Ex: our 16'x16' 4-season pergola can handle 88lbs of snow/ice per square foot. The smaller sizes can handle even more, while a 4-season 20'x20' can handle 50lbs/sqft. That's 2ft and 3ft of wet snow respectively.": { EN: "Ex: our 16'x16' 4-season pergola can handle 88lbs of snow/ice per square foot. The smaller sizes can handle even more, while a 4-season 20'x20' can handle 50lbs/sqft. That's 2ft and 3ft of wet snow respectively.", FR: "Ex : notre pergola 4 saisons de 16'x16' peut supporter 88 lb de neige/glace par pied carré. Cela représente 2 pieds et 3 pieds de neige mouillée." },
  "All 3 (Classic 3-season / Classic 4-season / Modern) can handle the mandated wind ratings of the entire United States and Canada, 160mph (but for very few exceptions in Southern Florida, the Keys). Remember, you are not limited to just 12ft in projection/depth. We've done our work and offer you the best materials and designs so you can cover the entire area. Should you require us to combine the pergolas together (ex: if your patio is 32ft wide and 18ft deep, we would make you a pergola with 6 posts, not 8 or more, to cover the entire area in 2 sections of 16'x18').": { EN: "All 3 (Classic 3-season / Classic 4-season / Modern) can handle the mandated wind ratings of the entire United States and Canada, 160mph (but for very few exceptions in Southern Florida, the Keys). Remember, you are not limited to just 12ft in projection/depth. We've done our work and offer you the best materials and designs so you can cover the entire area. Should you require us to combine the pergolas together (ex: if your patio is 32ft wide and 18ft deep, we would make you a pergola with 6 posts, not 8 or more, to cover the entire area in 2 sections of 16'x18').", FR: "Les 3 modèles peuvent supporter les cotes de vent obligatoires (160 mph). Si vous nous demandez de combiner les pergolas, nous ferons une pergola avec 6 poteaux, et non 8 ou plus." },
  'WHAT SIZES DO YOU OFFER? WHAT ARE YOUR STANDARD SIZES AND CAN WE CREATE OUR OWN?': { EN: 'WHAT SIZES DO YOU OFFER? WHAT ARE YOUR STANDARD SIZES AND CAN WE CREATE OUR OWN?', FR: 'QUELLES TAILLES OFFREZ-VOUS ? POUVONS-NOUS CRÉER LA NÔTRE ?' },
  "First the Standard Sizes. Our standard size pergolas start at 10'x10' and move up to 20'x20' in 2' increments in both width and projection, while still using only 4 posts. You can order a 14'x10' as easily as a 20'x16' pergola in all three variants.": { EN: "First the Standard Sizes. Our standard size pergolas start at 10'x10' and move up to 20'x20' in 2' increments in both width and projection, while still using only 4 posts. You can order a 14'x10' as easily as a 20'x16' pergola in all three variants.", FR: "D'abord les tailles standards. Nos pergolas de taille standard commencent à 10'x10' et vont jusqu'à 20'x20' par incréments de 2'." },
  'If you are placing your pergola further from the house, away from the home or patio (what we call a Freestanding Pergola), then most likely a Standard Size will do just fine. Should you wish to size it down by removing a few inches in any direction to make it fit, we will do so for free.': { EN: 'If you are placing your pergola further from the house, away from the home or patio (what we call a Freestanding Pergola), then most likely a Standard Size will do just fine. Should you wish to size it down by removing a few inches in any direction to make it fit, we will do so for free.', FR: 'Si vous placez votre pergola plus loin de la maison, une taille standard fera l\'affaire. Si vous souhaitez la réduire de quelques pouces pour l\'ajuster, nous le ferons gratuitement.' },
  "Ex: You have the perfect spot to place a 16' wide by 15' pergola, but we sell them in 2' increments. You would order a 16x16 then ask to have the depth/projection cut down by a foot, or even to the 1/32nd of an inch if that's what it's going to take to make it fit just right.": { EN: "Ex: You have the perfect spot to place a 16' wide by 15' pergola, but we sell them in 2' increments. You would order a 16x16 then ask to have the depth/projection cut down by a foot, or even to the 1/32nd of an inch if that's what it's going to take to make it fit just right.", FR: "Ex : Vous commanderiez un 16x16 puis demanderiez à ce que la profondeur soit réduite d'un pied pour qu'elle s'ajuste parfaitement." },
  'Standard Size pergolas can be customized by removing material. If you require to add length or depth, then we would charge one size up.': { EN: 'Standard Size pergolas can be customized by removing material. If you require to add length or depth, then we would charge one size up.', FR: 'Les pergolas de taille standard peuvent être personnalisées en retirant du matériel.' },
  "We can make L-shape pergolas without any issue. We can also work with you or your design team/landscaper to find a solution for your oddly shaped patio. We would collaborate on Canva.com via our account (no need to sign up) and come up with a solution to cover all or part of the deck/patio. If you have an eavestrough, we can work with that. If you have stairs in the way, we can work with that. If you have a bay window, we can work with that. If you have a patio that is 12' deep and have a BBQ placed right after on the ground floor, we can work with that by placing extended louvres, so that you can get out of your house, all the way down to the BBQ and back without a single drop hitting your steak!": { EN: "We can make L-shape pergolas without any issue...", FR: "Nous pouvons réaliser des pergolas en L sans aucun problème. Si vous avez des gouttières, des escaliers, ou une baie vitrée, nous pouvons nous y adapter." },
  "We've done simple projects that are 60' wide by 22' deep perfect rectangles as easily as an L-shape pergola that has 40' one way and another 18' on the small side, all while being 12ft high.": { EN: "We've done simple projects that are 60' wide by 22' deep perfect rectangles as easily as an L-shape pergola that has 40' one way and another 18' on the small side, all while being 12ft high.", FR: "Nous avons réalisé des projets de 60' de large par 22' de profondeur, aussi facilement qu'une pergola en forme de L de 40' d'un côté et 18' de l'autre." },
  'The secret is in the materials. Nobody, I mean nobody has louvres that weigh 2lbs a linear foot or a beam that weighs 5lbs a foot, not square foot, linear foot. That is serious strength. You can see images on the technical page.': { EN: 'The secret is in the materials. Nobody, I mean nobody has louvres that weigh 2lbs a linear foot or a beam that weighs 5lbs a foot, not square foot, linear foot. That is serious strength. You can see images on the technical page.', FR: 'Le secret réside dans les matériaux. Personne n\'a des lames qui pèsent 2 lb le pied linéaire. C\'est une résistance sérieuse.' },
  'Throw us a challenge!!': { EN: 'Throw us a challenge!!', FR: 'Lancez-nous un défi !!' },

  // --- Missing Engineering & Certification FAQs ---
  'As mentioned elsewhere on our site, we are proudly certified to be ASCE 7-16 and CNB-2020. You can install our pergolas in any state and feel confident that it will not have any permitting issues.': { EN: 'As mentioned elsewhere on our site, we are proudly certified to be ASCE 7-16 and CNB-2020. You can install our pergolas in any state and feel confident that it will not have any permitting issues.', FR: 'Comme mentionné ailleurs sur notre site, nous sommes fiers d\'être certifiés ASCE 7-16 et CNB-2020. Vous pouvez installer nos pergolas dans n\'importe quel état et être assuré qu\'il n\'y aura aucun problème de permis.' },
  'Our wind rating is 170 miles an hour (MPH) and snow load capacity, though slightly different by size, all exceed the required norms for almost the entire country (few cities with extreme snow will need some sizing changes, ex: going from 20ft between posts/columns down to 16ft).': { EN: 'Our wind rating is 170 miles an hour (MPH) and snow load capacity, though slightly different by size, all exceed the required norms for almost the entire country (few cities with extreme snow will need some sizing changes, ex: going from 20ft between posts/columns down to 16ft).', FR: 'Notre résistance au vent est de 170 miles à l\'heure (MPH) et la capacité de charge de neige, bien que légèrement différente selon la taille, dépasse toutes les normes requises pour presque tout le pays.' },
  'Should your city or State require any viewing of our documentation, feel free to reach out to make it happen. We will gladly help with the permitting process by giving you your pergola\'s spec sheet and any other municipality/city requirements. Again, getting engineers to approve and sign off for ASCE 7-16 standards was no easy task, but we did it.': { EN: 'Should your city or State require any viewing of our documentation, feel free to reach out to make it happen. We will gladly help with the permitting process by giving you your pergola\'s spec sheet and any other municipality/city requirements. Again, getting engineers to approve and sign off for ASCE 7-16 standards was no easy task, but we did it.', FR: 'Si votre ville ou état exige de consulter notre documentation, n\'hésitez pas à nous contacter. Nous vous aiderons avec plaisir dans le processus de permis en vous fournissant la fiche technique. Obtenir l\'approbation des ingénieurs pour les normes ASCE 7-16 n\'a pas été une tâche facile, mais nous l\'avons fait.' },
  'Some key points in this section are:': { EN: 'Some key points in this section are:', FR: 'Certains points clés de cette section sont :' },
  'Key Point 1: If you are placing the pergola away from your home, on pavers near the pool or anywhere not on the deck, then you can choose and will usually be fine with our standard sizes. No customization is usually required for these orders.': { EN: 'Key Point 1: If you are placing the pergola away from your home, on pavers near the pool or anywhere not on the deck, then you can choose and will usually be fine with our standard sizes. No customization is usually required for these orders.', FR: 'Point clé 1 : Si vous placez la pergola loin de votre maison, sur des pavés ou près de la piscine, vous pouvez choisir et vous contenter de nos tailles standards. Aucune personnalisation n\'est généralement requise.' },
  'However, if you are placing the pergola on your deck, or would like to cover an area that has a funky shape, please give us a call. We can customize your pergola down to the 32nd of an inch, so that it can be integrated into your deck railings.': { EN: 'However, if you are placing the pergola on your deck, or would like to cover an area that has a funky shape, please give us a call. We can customize your pergola down to the 32nd of an inch, so that it can be integrated into your deck railings.', FR: 'Cependant, si vous la placez sur votre terrasse, ou si vous souhaitez couvrir une zone avec une forme originale, appelez-nous. Nous pouvons personnaliser votre pergola au 32ème de pouce.' },
  'Key Point 2: Our louvres are so strong, they can pass the pergola frame by up to 48 inches.': { EN: 'Key Point 2: Our louvres are so strong, they can pass the pergola frame by up to 48 inches.', FR: 'Point clé 2 : Nos lames sont si solides qu\'elles peuvent dépasser le cadre de la pergola jusqu\'à 48 pouces.' },
  'Key Point 3: The specs on our standard size pergolas are available in the series of images at the bottom when you choose your size. Height, center-center etc. can be seen when you choose the size.': { EN: 'Key Point 3: The specs on our standard size pergolas are available in the series of images at the bottom when you choose your size. Height, center-center etc. can be seen when you choose the size.', FR: 'Point clé 3 : Les spécifications de nos pergolas de taille standard sont disponibles dans la série d\'images en bas lorsque vous choisissez votre taille.' },
  'Key Point 4: The standard height columns of our Classic Pergolas are 90in / 7ft 6in. The standard height of the columns of our Modern Pergolas are 96in / 8ft. That is the clearance below the perimeter frame beams. There is another 18in of clearance underneath.': { EN: 'Key Point 4: The standard height columns of our Classic Pergolas are 90in / 7ft 6in. The standard height of the columns of our Modern Pergolas are 96in / 8ft. That is the clearance below the perimeter frame beams. There is another 18in of clearance underneath.', FR: 'Point clé 4 : La hauteur standard des colonnes de nos Pergolas Classiques est de 90po / 7pi 6po. La hauteur standard des colonnes de nos Pergolas Modernes est de 96po / 8pi. C\'est le dégagement sous les poutres.' },
  'Should you require any height adjustment, we can adjust to your preference or need. There is no cost to lower the column, but there is a cost for the next bracket up. The extended columns go up to 126in / 10ft 6in and cost a little more. You can choose any height between 91in and 126in. We will cut them according to your needs.': { EN: 'Should you require any height adjustment, we can adjust to your preference or need. There is no cost to lower the column, but there is a cost for the next bracket up. The extended columns go up to 126in / 10ft 6in and cost a little more. You can choose any height between 91in and 126in. We will cut them according to your needs.', FR: 'Si vous avez besoin d\'un ajustement de hauteur, nous pouvons l\'ajuster à votre préférence. Il n\'y a aucun coût pour abaisser la colonne, mais un coût s\'applique pour le support supérieur. Les colonnes allongées vont jusqu\'à 126po et coûtent un peu plus cher.' },
  'Again, remember the roof of the pergola, inside the Classic Pergola is higher by 18in (3 and 4 Season) and 12in for the Modern Pergola.': { EN: 'Again, remember the roof of the pergola, inside the Classic Pergola is higher by 18in (3 and 4 Season) and 12in for the Modern Pergola.', FR: 'Encore une fois, n\'oubliez pas que le toit de la pergola, à l\'intérieur de la Pergola Classique, est plus haut de 18po (3 et 4 Saisons) et de 12po pour la Pergola Moderne.' },
  'We can work on the specs together to make things fit perfectly. You have the basic measurements in the gallery as you choose each size.': { EN: 'We can work on the specs together to make things fit perfectly. You have the basic measurements in the gallery as you choose each size.', FR: 'Nous pouvons travailler sur les spécifications ensemble pour que tout s\'ajuste parfaitement. Vous avez les mesures de base dans la galerie lorsque vous choisissez chaque taille.' },

  // --- Missing Technical & Table Properties ---
  'Feature': { EN: 'Feature', FR: 'Caractéristique' },
  'Louvres lock at any angle': { EN: 'Louvres lock at any angle', FR: 'Les lames se verrouillent à n\'importe quel angle' },
  'Manual mechanism': { EN: 'Manual mechanism', FR: 'Mécanisme manuel' },
  'Electric mechanism option': { EN: 'Electric mechanism option', FR: 'Option de mécanisme électrique' },
  'Built-in rails for curtains (left to right)': { EN: 'Built-in rails for curtains (left to right)', FR: 'Rails intégrés pour rideaux (gauche à droite)' },
  'Electric curtains (vertical movement)': { EN: 'Electric curtains (vertical movement)', FR: 'Rideaux électriques (mouvement vertical)' },
  'Heavy-gauge aluminum': { EN: 'Heavy-gauge aluminum', FR: 'Aluminium de forte épaisseur' },
  'Rain run-off': { EN: 'Rain run-off', FR: 'Écoulement de la pluie' },
  'Grade 8 bolts (McMaster: 90128A714)': { EN: 'Grade 8 bolts (McMaster: 90128A714)', FR: 'Boulons de grade 8 (McMaster: 90128A714)' },
  '4-season capable': { EN: '4-season capable', FR: 'Capable de 4 saisons' },
  'Integrated gutters': { EN: 'Integrated gutters', FR: 'Gouttières intégrées' },
  'Up to 20ft': { EN: 'Up to 20ft', FR: 'Jusqu\'à 20 pieds' },
  'LockDrives': { EN: 'LockDrives', FR: 'LockDrives' },
  'Somfy': { EN: 'Somfy', FR: 'Somfy' },
  'Clip on Table': { EN: 'Clip on Table', FR: 'Table à clipser' },

  // --- Missing Labels ---
  '100% CANADIAN PRODUCTION': { EN: '100% CANADIAN PRODUCTION', FR: 'PRODUCTION 100% CANADIENNE' },
  'Canada': { EN: 'Canada', FR: 'Canada' },
  'United States': { EN: 'United States', FR: 'États-Unis' },
  'Mexico': { EN: 'Mexico', FR: 'Mexique' },
  'Address: 25 Shaft Road, Etobicoke, Ontario, Canada': { EN: 'Address: 25 Shaft Road, Etobicoke, Ontario, Canada', FR: 'Adresse : 25 Shaft Road, Etobicoke, Ontario, Canada' },
  'Address: 437 Catherine St, Ottawa, ON Canada K1R 5T7': { EN: 'Address: 437 Catherine St, Ottawa, ON Canada K1R 5T7', FR: 'Adresse : 437 Catherine St, Ottawa, ON Canada K1R 5T7' },
  '115 Dundas St. W.': { EN: '115 Dundas St. W.', FR: '115 rue Dundas O.' },
  'Highway #5, Clappison Corners': { EN: 'Highway #5, Clappison Corners', FR: 'Route #5, Clappison Corners' },
  'Dundas, Ontario, Canada': { EN: 'Dundas, Ontario, Canada', FR: 'Dundas, Ontario, Canada' },
  '12,500$-14,999$': { EN: '12,500$-14,999$', FR: '12 500 $ - 14 999 $' },
  '15,000$-20,000$': { EN: '15,000$-20,000$', FR: '15 000 $ - 20 000 $' },
  '20,000$-25,000$': { EN: '20,000$-25,000$', FR: '20 000 $ - 25 000 $' },
  '25,000$+': { EN: '25,000$+', FR: '25 000 $ +' },
  
  // --- Missing Blog Post Info ---
  'Pergola Buyer Checklist: 5 Questions That Separate Premium Structures from the Rest': { EN: 'Pergola Buyer Checklist: 5 Questions That Separate Premium Structures from the Rest', FR: 'Liste de contrôle : 5 questions qui distinguent les structures haut de gamme' },
  'Built for Canada: How the National Building Code Drives Mr. Pergola’s Engineering': { EN: 'Built for Canada: How the National Building Code Drives Mr. Pergola’s Engineering', FR: 'Conçu pour le Canada : Comment le code du bâtiment guide l\'ingénierie de Mr. Pergola' },
  'How Pergolas With Rotating Slats Can Boost Your Home Value by 80%+ (Montreal Homeowner’s Guide)': { EN: 'How Pergolas With Rotating Slats Can Boost Your Home Value by 80%+ (Montreal Homeowner’s Guide)', FR: 'Comment les pergolas peuvent augmenter la valeur de votre maison (Guide montréalais)' },
  'Transforming Outdoor Living: The Comprehensive Guide to Aluminum Bioclimatic Pergolas': { EN: 'Transforming Outdoor Living: The Comprehensive Guide to Aluminum Bioclimatic Pergolas', FR: 'Transformer la vie en plein air : Le guide des pergolas bioclimatiques en aluminium' },
  'The Beauty and Durability of Aluminum Pergolas: Transforming Gardens Everywhere': { EN: 'The Beauty and Durability of Aluminum Pergolas: Transforming Gardens Everywhere', FR: 'La beauté et la durabilité des pergolas en aluminium : Transformer les jardins' },
  'Pergola Protectors: How to Select a Superhero for Your Outdoor Space': { EN: 'Pergola Protectors: How to Select a Superhero for Your Outdoor Space', FR: 'Protecteurs de pergola : Comment choisir un super-héros pour l\'extérieur' },
  'From Production to Perfection: The Journey of High-Quality Aluminum Pergolas': { EN: 'From Production to Perfection: The Journey of High-Quality Aluminum Pergolas', FR: 'De la production à la perfection : Le parcours des pergolas en aluminium' },
  'Evaluating the Weight of Quality: The Significance of Aluminum Density in Pergola Construction': { EN: 'Evaluating the Weight of Quality: The Significance of Aluminum Density in Pergola Construction', FR: 'Évaluer la qualité : L\'importance de la densité de l\'aluminium en construction' },
  'Guides': { EN: 'Guides', FR: 'Guides' },
  'Engineering': { EN: 'Engineering', FR: 'Ingénierie' },
  'Investment': { EN: 'Investment', FR: 'Investissement' },
  'Design': { EN: 'Design', FR: 'Design' },
  'Lifestyle': { EN: 'Lifestyle', FR: 'Mode de vie' },
  'Manufacturing': { EN: 'Manufacturing', FR: 'Fabrication' },
  'May 20, 2024': { EN: 'May 20, 2024', FR: '20 mai 2024' },
  'May 12, 2024': { EN: 'May 12, 2024', FR: '12 mai 2024' },
  'April 28, 2024': { EN: 'April 28, 2024', FR: '28 avril 2024' },
  'April 15, 2024': { EN: 'April 15, 2024', FR: '15 avril 2024' },
  'March 22, 2024': { EN: 'March 22, 2024', FR: '22 mars 2024' },
  'March 05, 2024': { EN: 'March 05, 2024', FR: '05 mars 2024' },
  'February 18, 2024': { EN: 'February 18, 2024', FR: '18 février 2024' },
  'February 02, 2024': { EN: 'February 02, 2024', FR: '02 février 2024' },

  // --- Missing Contact Labels ---
  'Head Office & Showroom': { EN: 'Head Office & Showroom', FR: 'Siège social et salle de montre' },
  'Head Office': { EN: 'Head Office', FR: 'Siège social' },
  'Toll Free': { EN: 'Toll Free', FR: 'Sans frais' },
  'Fax': { EN: 'Fax', FR: 'Télécopieur' },
  'E-mail': { EN: 'E-mail', FR: 'Courriel' },
  'Tel': { EN: 'Tel', FR: 'Tél' },
  'Website': { EN: 'Website', FR: 'Site Web' },
  'Downtown landscape depot at 437 Catherine Street': { EN: 'Downtown landscape depot at 437 Catherine Street', FR: 'Dépôt paysager du centre-ville au 437 rue Catherine' },
  'Skyscapes Outdoor Flooring & Decor - Balcony & Patio Flooring in Toronto': { EN: 'Skyscapes Outdoor Flooring & Decor - Balcony & Patio Flooring in Toronto', FR: 'Skyscapes Outdoor Flooring & Decor - Plancher de balcon et patio à Toronto' },

  // Newly Added Core Translations
  'About Us': { EN: 'About Us', FR: 'À propos de nous' },
  'The': { EN: 'The', FR: 'L\'' },
  'Story': { EN: 'Story', FR: 'histoire' },
  'Behind It All.': { EN: 'Behind It All.', FR: 'derrière tout ça.' },
  'Inside Our Workshop': { EN: 'Inside Our Workshop', FR: 'À l\'intérieur de notre atelier' },
  'From my home to yours,': { EN: 'From my home to yours,', FR: 'De ma maison à la vôtre,' },
  'Contact us for any questions': { EN: 'Contact us for any questions', FR: 'Contactez-nous pour toute question' },
  'Read more about Mr. Pergola': { EN: 'Read more about Mr. Pergola', FR: 'En savoir plus sur Mr. Pergola' },
  'View Gallery': { EN: 'View Gallery', FR: 'Voir la Galerie' },
  'Contact Us': { EN: 'Contact Us', FR: 'Contactez-nous' },
  'Call': { EN: 'Call', FR: 'Appeler' },
  'CALL:': { EN: 'CALL:', FR: 'APPEL :' },
  'TOLL FREE:': { EN: 'TOLL FREE:', FR: 'SANS FRAIS :' },
  'TEXT ONLY:': { EN: 'TEXT ONLY:', FR: 'TEXTO SEULEMENT :' },
  'Email': { EN: 'Email', FR: 'Courriel' },
  'For Service:': { EN: 'For Service:', FR: 'Pour le service :' },
  'Address & Hours': { EN: 'Address & Hours', FR: 'Adresse et Heures' },
  'Monday to Friday:': { EN: 'Monday to Friday:', FR: 'Lundi au vendredi :' },
  'Saturday & Sunday:': { EN: 'Saturday & Sunday:', FR: 'Samedi et dimanche :' },
  'By appointment only (available with one-hour advance notice).': { EN: 'By appointment only (available with one-hour advance notice).', FR: 'Sur rendez-vous uniquement (disponible avec un préavis d\'une heure).' },
  'Get a Quote': { EN: 'Get a Quote', FR: 'Obtenir une Soumission' },
  'First Name *': { EN: 'First Name *', FR: 'Prénom *' },
  'First Name': { EN: 'First Name', FR: 'Prénom' },
  'Last Name *': { EN: 'Last Name *', FR: 'Nom de famille *' },
  'Last Name': { EN: 'Last Name', FR: 'Nom de famille' },
  'Email *': { EN: 'Email *', FR: 'Courriel *' },
  'Phone/Mobile *': { EN: 'Phone/Mobile *', FR: 'Téléphone/Mobile *' },
  'Phone/Mobile': { EN: 'Phone/Mobile', FR: 'Téléphone/Mobile' },
  'Address Line 1 *': { EN: 'Address Line 1 *', FR: 'Adresse Ligne 1 *' },
  'Address Line 1': { EN: 'Address Line 1', FR: 'Adresse Ligne 1' },
  'Address Line 2': { EN: 'Address Line 2', FR: 'Adresse Ligne 2' },
  'City *': { EN: 'City *', FR: 'Ville *' },
  'City': { EN: 'City', FR: 'Ville' },
  'State/Province *': { EN: 'State/Province *', FR: 'État/Province *' },
  'State/Province': { EN: 'State/Province', FR: 'État/Province' },
  'Zip Code/Postal Code *': { EN: 'Zip Code/Postal Code *', FR: 'Code Postal *' },
  'Zip Code/Postal Code': { EN: 'Zip Code/Postal Code', FR: 'Code Postal' },
  'Country *': { EN: 'Country *', FR: 'Pays *' },
  'Project Type': { EN: 'Project Type', FR: 'Type de Projet' },
  'Residential': { EN: 'Residential', FR: 'Résidentiel' },
  'Commercial': { EN: 'Commercial', FR: 'Commercial' },
  'Type of surface on which the pergola will be installed': { EN: 'Type of surface on which the pergola will be installed', FR: 'Type de surface sur laquelle la pergola sera installée' },
  'Grass': { EN: 'Grass', FR: 'Gazon' },
  'Concrete': { EN: 'Concrete', FR: 'Béton' },
  'Wood': { EN: 'Wood', FR: 'Bois' },
  'Other': { EN: 'Other', FR: 'Autre' },
  'Location': { EN: 'Location', FR: 'Emplacement' },
  'Ground Level': { EN: 'Ground Level', FR: 'Au sol' },
  'Raised (Patio/Rooftop)': { EN: 'Raised (Patio/Rooftop)', FR: 'Surélevé (Patio/Toit)' },
  'Desired Size of Pergola (Length determines the length of each louvre / Width determines the amount of louvres left to right)': { EN: 'Desired Size of Pergola...', FR: 'Taille désirée de la Pergola (La longueur détermine la longueur de chaque lame / La largeur détermine la quantité de lames de gauche à droite)' },
  'Please fill the length and width below': { EN: 'Please fill the length and width below', FR: 'Veuillez remplir la longueur et la largeur ci-dessous' },
  'Length *': { EN: 'Length *', FR: 'Longueur *' },
  'Length': { EN: 'Length', FR: 'Longueur' },
  'Width *': { EN: 'Width *', FR: 'Largeur *' },
  'Width': { EN: 'Width', FR: 'Largeur' },
  'Color *': { EN: 'Color *', FR: 'Couleur *' },
  'Black': { EN: 'Black', FR: 'Noir' },
  'White': { EN: 'White', FR: 'Blanc' },
  'Budget *': { EN: 'Budget *', FR: 'Budget *' },
  'Please include at least 2 pictures of the area where pergola will be installed': { EN: 'Please include at least 2 pictures of the area where pergola will be installed', FR: 'Veuillez inclure au moins 2 photos de la zone où la pergola sera installée' },
  'Max. file size: 128 MB.': { EN: 'Max. file size: 128 MB.', FR: 'Taille max. du fichier : 128 Mo.' },
  'Message': { EN: 'Message', FR: 'Message' },
  'Ottawa Area Please Contact Mr.Pergola Directly': { EN: 'Ottawa Area Please Contact Mr.Pergola Directly', FR: 'Région d\'Ottawa, veuillez contacter Mr. Pergola directement' },
  'Greater Toronto Area': { EN: 'Greater Toronto Area', FR: 'Région du Grand Toronto' },
  'Calgary and Alberta': { EN: 'Calgary and Alberta', FR: 'Calgary et Alberta' },
  'Archives': { EN: 'Archives', FR: 'Archives' },
  'Insights &': { EN: 'Insights &', FR: 'Aperçus &' },
  'Inspiration.': { EN: 'Inspiration.', FR: 'Inspiration.' },
  'Read More': { EN: 'Read More', FR: 'Lire la Suite' },
  'Back to Blog': { EN: 'Back to Blog', FR: 'Retour au Blog' },
  'Article Not Found': { EN: 'Article Not Found', FR: 'Article Introuvable' },
  'Return to Blog': { EN: 'Return to Blog', FR: 'Retourner au Blog' },
  'Admin Console': { EN: 'Admin Console', FR: 'Console d\'Administration' },
  'Settings': { EN: 'Settings', FR: 'Paramètres' },
  'Log Out': { EN: 'Log Out', FR: 'Se Déconnecter' },
  'New Inquiries': { EN: 'New Inquiries', FR: 'Nouvelles Demandes' },
  'Active Leads': { EN: 'Active Leads', FR: 'Prospects Actifs' },
  'Published Posts': { EN: 'Published Posts', FR: 'Articles Publiés' },
  'System Health': { EN: 'System Health', FR: 'Santé du Système' },
  'Admin Notes': { EN: 'Admin Notes', FR: 'Notes de l\'Admin' },
  'Control Panel Login': { EN: 'Control Panel Login', FR: 'Connexion au Panneau de Configuration' },
  'Sign In': { EN: 'Sign In', FR: 'Se Connecter' },
  'Username': { EN: 'Username', FR: 'Nom d\'utilisateur' },
  'Enter username': { EN: 'Enter username', FR: 'Entrez le nom d\'utilisateur' },
  'Password': { EN: 'Password', FR: 'Mot de passe' },
  'Enter password': { EN: 'Enter password', FR: 'Entrez le mot de passe' },
  'Admin Access': { EN: 'Admin Access', FR: 'Accès Admin' },
  'HERE IS EVERYTHING YOU WANT TO KNOW': { EN: 'HERE IS EVERYTHING YOU WANT TO KNOW', FR: 'VOICI TOUT CE QUE VOUS VOULEZ SAVOIR' },
  'Some important questions': { EN: 'Some important questions', FR: 'Quelques questions importantes' },
  'CUSTOM PERGOLAS: THIS IS WHERE WE SHINE!': { EN: 'CUSTOM PERGOLAS: THIS IS WHERE WE SHINE!', FR: 'PERGOLAS SUR MESURE : C\'EST LÀ QUE NOUS EXCELLONS !' },
  'COLORS': { EN: 'COLORS', FR: 'COULEURS' },
  'INSTALLATION / ASSEMBLY': { EN: 'INSTALLATION / ASSEMBLY', FR: 'INSTALLATION / ASSEMBLAGE' },
  'CERTIFICATION AND ENGINEERING': { EN: 'CERTIFICATION AND ENGINEERING', FR: 'CERTIFICATION ET INGÉNIERIE' },
  'Elevate Your Experience.': { EN: 'Elevate Your Experience.', FR: 'Améliorez votre expérience.' },
  'Discover Our Premium Additions': { EN: 'Discover Our Premium Additions', FR: 'Découvrez nos ajouts haut de gamme' },
  'Now Available': { EN: 'Now Available', FR: 'Maintenant disponible' },
  'Featured Highlights': { EN: 'Featured Highlights', FR: 'Faits saillants' },
  'All Accessories': { EN: 'All Accessories', FR: 'Tous les accessoires' },
  'The Complete Collection': { EN: 'The Complete Collection', FR: 'La collection complète' },
  'Somfy Compatible': { EN: 'Somfy Compatible', FR: 'Compatible Somfy' },
  'Mosquito Netting': { EN: 'Mosquito Netting', FR: 'Moustiquaire' },
  'Privacy Slats': { EN: 'Privacy Slats', FR: 'Lames d\'Intimité' },
  'Option Solarium (OPEN)': { EN: 'Option Solarium (OPEN)', FR: 'Option Solarium (OUVERT)' },
  'Option Solarium (CLOSED)': { EN: 'Option Solarium (CLOSED)', FR: 'Option Solarium (FERMÉ)' },
  'Flowerpot': { EN: 'Flowerpot', FR: 'Pot de fleurs' },
  'Flowerpot Hanger': { EN: 'Flowerpot Hanger', FR: 'Support de pot de fleurs' },
  'Clip On Table': { EN: 'Clip On Table', FR: 'Table à clipser' },
  'Heavy Suspension System': { EN: 'Heavy Suspension System', FR: 'Système de suspension lourd' },
  'Hammock Suspension System': { EN: 'Hammock Suspension System', FR: 'Système pour hamac' },
  'Light Object Hangar System': { EN: 'Light Object Hangar System', FR: 'Système pour objets légers' },
  'Classic vs Modern': { EN: 'Classic vs Modern', FR: 'Classique vs Moderne' },
  'Certified 4-Season': { EN: 'Certified 4-Season', FR: 'Certification 4-Saisons jusqu`à 20x20' },
  'Certified 4-Season Pergola': { EN: 'Certified 4-Season Pergola', FR: 'Pergola Certifiée 4 Saisons jusqu`à 20x20' },
};

const allTranslations = { ...translations, ...supplementalTranslations };

// Normalize strings to ignore line breaks and extra spaces from JSX formatting
const normalize = (str: string) => str.replace(/\s+/g, ' ').trim();

// Build i18next resources dynamically to prevent casing mismatches
const resources = {
  EN: { translation: {} as Record<string, string> },
  FR: { translation: {} as Record<string, string> },
  en: { translation: {} as Record<string, string> },
  fr: { translation: {} as Record<string, string> }
};

for (const [key, value] of Object.entries(allTranslations)) {
  const normalizedKey = normalize(key);
  resources.EN.translation[normalizedKey] = value.EN;
  resources.FR.translation[normalizedKey] = value.FR;
  resources.en.translation[normalizedKey] = value.EN;
  resources.fr.translation[normalizedKey] = value.FR;
}

i18n
  .use(LanguageDetector)
  .use(initReactI18next)
  .init({
    resources,
    fallbackLng: 'en',
    detection: {
      order: ['localStorage', 'navigator'],
      lookupLocalStorage: 'language', // Maps seamlessly to your old localStorage key
      caches: ['localStorage'],
    },
    interpolation: {
      escapeValue: false, // React inherently protects from XSS
    },
  });

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const { i18n: i18nInstance } = useTranslation();

  useEffect(() => {
    const lang = i18nInstance.language?.toLowerCase().startsWith('fr') ? 'fr' : 'en';
    document.documentElement.lang = lang;
  }, [i18nInstance.language]);

  return <>{children}</>;
}

export function useLanguage(): LanguageContextType {
  const { t: i18nT, i18n: i18nInstance } = useTranslation();
  
  const language = (i18nInstance.language?.toUpperCase().startsWith('FR') ? 'FR' : 'EN') as Language;
  
  const setLanguage = useCallback((lang: Language) => {
    i18nInstance.changeLanguage(lang.toLowerCase());
  }, [i18nInstance]);

  const t = useCallback((key: string) => {
    if (!key) return '';
    const normalizedKey = normalize(key);
    return i18nT(normalizedKey as any, { defaultValue: key }) as string;
  }, [i18nT]);

  return { language, setLanguage, t };
}
